### ISSUE TITLE
Create lambda that can invalidate parts of the website on update

### ISSUE THREAD

**Issue by Kelvinrr** [DOI-USGS/asc-public-docs#13]
Cloudfront caching helps save money but can also prevent changes from being published right away. We can avoid this by creating an [invalidation](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html) of the files when an MR is merged via a lambda. lambdas can be setup to trigger when there is an update to the bucket so it doesn't need to run on our CI/CD pipelines.

Since going public, when we push changes they are seen immediately so it might be worth investigating if the cache is still being used.

**Comment by jrcain-usgs** [comment]
We have a cloudfront and route53 for docs.astrogeology.usgs.gov that looks like it only works internally.  Should that be made publicly accessible, or maybe removed?

**Comment by jrcain-usgs** [comment]
The part of the setup that is important here seems to be out of the hands of the dev team.  Closing this, will leave related concerns up to those who manage the astrogeology.usgs.gov domain.
