### ISSUE TITLE
Concept Doc: Create a doc that would explain the relationship between ISIS, ALE, and CSM

### ISSUE THREAD

**Issue by Kelvinrr** [DOI-USGS/asc-public-docs#31]
Basically, a more up to date version of this paper by Jay and Jesse: https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2019EA000713

We need to include things that have changed and things the paper hasn't mentioned: 

* Bundle Adjustment 
* Exporting updated orientations from ISDs
* Extended ecosystem (ASP, GXP) and their capabilities 
* Grounded Sensor Support

**Comment by AustinSanders** [comment]
The docs in #36 were intended to resolve this issue.  Those docs include some basic information on jigsaw / bundle adjustment, ASP/GXP + the ASC ecosystem, and a brief discussion of model statefulness + ISDs, but they don't include information on grounded sensor support.

I'm not really sure what to say about grounded sensor support.

**Comment by Kelvinrr** [comment]
I think we can close this one, we can make another one for grounded sensor support in a separate issue when it's more fleshed out.
