### ISSUE TITLE
Find what is left from the old ISIS docs and move it here 

### ISSUE THREAD

**Issue by Kelvinrr** [DOI-USGS/asc-public-docs#50]
Find anything on value on the old ISIS docs (https://isis.astrogeology.usgs.gov/8.1.0/) and identify what else can be moved here. Those old docs are not compliant and seem to be code rotting. Some things to consider: 

1. Could there be a way to move the doxygen apps here as a new site? Maybe using mkdocs. 
2. The most useful thing by far are the app descriptions. Can we migrate those to a mkdocs page? If not, start removing things that are 404-ing. 
3. For any page that feels valuable to migrate, open a separate issue for them.

**Comment by amystamile-usgs** [comment]
List of document pages to possibly merge:

- [ ] https://isis.astrogeology.usgs.gov/8.1.0/documents/BackwardCompatibility/BackwardCompatibility.html
- [ ] https://isis.astrogeology.usgs.gov/8.1.0/documents/CodingStandards/CodingStandards.html
- [ ] https://isis.astrogeology.usgs.gov/8.1.0/documents/CommandLine/CommandLine.html
- [ ] https://isis.astrogeology.usgs.gov/8.1.0/documents/ControlNetworks/index.html
- [ ] https://isis.astrogeology.usgs.gov/8.1.0/documents/Conversion/Conversion.html
- [ ] https://isis.astrogeology.usgs.gov/8.1.0/documents/ErrorDictionary/ErrorDictionary.html
- [ ] https://isis.astrogeology.usgs.gov/8.1.0/documents/ErrorHandlingFacility/ErrorHandlingFacility.html
- [ ] https://isis.astrogeology.usgs.gov/8.1.0/documents/Glossary/Glossary.html
- [ ] https://isis.astrogeology.usgs.gov/8.1.0/documents/HowToGeneralDocumentation/index.html
- [ ] https://isis.astrogeology.usgs.gov/8.1.0/documents/IsisHistory/IsisHistory.html
- [ ] https://isis.astrogeology.usgs.gov/8.1.0/documents/LabelDictionary/LabelDictionary.html
- [ ] https://isis.astrogeology.usgs.gov/8.1.0/documents/LogicalCubeFormatGuide/LogicalCubeFormatGuide.html
- [ ] https://isis.astrogeology.usgs.gov/8.1.0/documents/Overview/Overview.html
- [ ] https://isis.astrogeology.usgs.gov/8.1.0/documents/PatternMatch/PatternMatch.html
- [ ] https://isis.astrogeology.usgs.gov/8.1.0/documents/PreferenceDictionary/PreferenceDictionary.html
- [ ] https://isis.astrogeology.usgs.gov/8.1.0/documents/SessionLogs/SessionLogs.html

**Comment by amystamile-usgs** [comment]
ISIS History page will be moved to drupal at some point. All other pages have been ported to new docs site.
