### ISSUE TITLE
ISIS Pattern Match

### ISSUE THREAD

**Issue by amystamile-usgs** [DOI-USGS/asc-public-docs#56]
https://isis.astrogeology.usgs.gov/8.1.0/documents/PatternMatch/PatternMatch.html

**Comment by lwellerastro** [comment]
Hi @amystamile-usgs - thanks for keeping the Pattern Matching document available, I still use it regularly for reminders. 

I agree a lot of what is in that document has been captured under the automatic-registration link (I didn't even know this was available), but the new page lacks some detail (I did not make a page to page comparison, so I might be wrong, but it looked thinner) and omits the figures which have helped me enormously in the past to understand the concepts involved. I imagine those figures might be embedded and not available or too difficult to migrate to the new page.

I realize this topic might be closed, but perhaps it makes sense to add a link to the Pattern Matching somewhere on Automatic Registration concepts page? There is a link to the Pattern Matching via the pointreg application help page, so maybe it's not necessary. I just don't know how one lands on the Docs or Concepts page to begin with to get to the new stuff, but maybe that's not a live link from git or the isis homepage. And maybe clearing up this confusion is the whole point of this and main docs PR.
